### ISSUE TITLE
npm install failed 

### ISSUE THREAD

**Issue by joeytat** [TheLarkInn/webpack-workshop-2018#39]
running npm install prints out "Cannot read property 'match' of undefined"

```
17 silly saveTree │ ├─┬ mkdirp@0.5.1
17 silly saveTree │ │ └── minimist@0.0.8
17 silly saveTree │ └── pify@4.0.1
17 silly saveTree ├─┬ css-loader@3.1.0
17 silly saveTree │ ├── camelcase@5.3.1
17 silly saveTree │ ├── cssesc@3.0.0
17 silly saveTree │ ├─┬ icss-utils@4.1.1
17 silly saveTree │ │ └─┬ postcss@7.0.17
17 silly saveTree │ │   ├── source-map@0.6.1
17 silly saveTree │ │   └─┬ supports-color@6.1.0
17 silly saveTree │ │     └── has-flag@3.0.0
17 silly saveTree │ ├── normalize-path@3.0.0
17 silly saveTree │ ├── postcss-modules-extract-imports@2.0.0
17 silly saveTree │ ├─┬ postcss-modules-local-by-default@3.0.2
17 silly saveTree │ │ ├─┬ postcss-selector-parser@6.0.2
17 silly saveTree │ │ │ └── indexes-of@1.0.1
17 silly saveTree │ │ └── postcss-value-parser@4.0.1
17 silly saveTree │ ├── postcss-modules-scope@2.1.0
17 silly saveTree │ ├── postcss-modules-values@3.0.0
17 silly saveTree │ ├── postcss-value-parser@4.0.1
17 silly saveTree │ └── postcss@7.0.17
17 silly saveTree ├─┬ d3@5.9.7
17 silly saveTree │ ├── d3-array@1.2.4
17 silly saveTree │ ├── d3-axis@1.0.12
17 silly saveTree │ ├─┬ d3-brush@1.1.0
17 silly saveTree │ │ ├── d3-dispatch@1.0.5
17 silly saveTree │ │ ├─┬ d3-drag@1.2.3
17 silly saveTree │ │ │ └── d3-selection@1.4.0
17 silly saveTree │ │ ├─┬ d3-interpolate@1.3.2
17 silly saveTree │ │ │ └── d3-color@1.3.0
17 silly saveTree │ │ ├── d3-selection@1.4.0
17 silly saveTree │ │ └─┬ d3-transition@1.2.0
17 silly saveTree │ │   ├── d3-ease@1.0.5
17 silly saveTree │ │   └── d3-timer@1.0.9
17 silly saveTree │ ├─┬ d3-chord@1.0.6
17 silly saveTree │ │ └── d3-path@1.0.8
17 silly saveTree │ ├── d3-collection@1.0.7
17 silly saveTree │ ├── d3-color@1.3.0
17 silly saveTree │ ├── d3-contour@1.3.2
17 silly saveTree │ ├── d3-dispatch@1.0.5
17 silly saveTree │ ├── d3-drag@1.2.3
17 silly saveTree │ ├─┬ d3-dsv@1.1.1
17 silly saveTree │ │ ├── commander@2.20.0
17 silly saveTree │ │ └── iconv-lite@0.4.24
17 silly saveTree │ ├── d3-ease@1.0.5
17 silly saveTree │ ├── d3-fetch@1.1.2
17 silly saveTree │ ├─┬ d3-force@1.2.1
17 silly saveTree │ │ └── d3-quadtree@1.0.6
17 silly saveTree │ ├── d3-format@1.3.2
17 silly saveTree │ ├── d3-geo@1.11.6
17 silly saveTree │ ├── d3-hierarchy@1.1.8
17 silly saveTree │ ├── d3-interpolate@1.3.2
17 silly saveTree │ ├── d3-path@1.0.8
17 silly saveTree │ ├── d3-polygon@1.0.5
17 silly saveTree │ ├── d3-quadtree@1.0.6
17 silly saveTree │ ├── d3-random@1.1.2
17 silly saveTree │ ├── d3-scale-chromatic@1.3.3
17 silly saveTree │ ├─┬ d3-scale@2.2.2
17 silly saveTree │ │ ├─┬ d3-time-format@2.1.3
17 silly saveTree │ │ │ └── d3-time@1.0.11
17 silly saveTree │ │ └── d3-time@1.0.11
17 silly saveTree │ ├── d3-selection@1.4.0
17 silly saveTree │ ├── d3-shape@1.3.5
17 silly saveTree │ ├── d3-time-format@2.1.3
17 silly saveTree │ ├── d3-time@1.0.11
17 silly saveTree │ ├── d3-timer@1.0.9
17 silly saveTree │ ├── d3-transition@1.2.0
17 silly saveTree │ ├── d3-voronoi@1.1.4
17 silly saveTree │ └── d3-zoom@1.7.3
17 silly saveTree ├── file-loader@4.1.0
17 silly saveTree ├─┬ fork-ts-checker-webpack-plugin@1.5.0
17 silly saveTree │ ├─┬ babel-code-frame@6.26.0
17 silly saveTree │ │ ├─┬ chalk@1.1.3
17 silly saveTree │ │ │ ├── ansi-styles@2.2.1
17 silly saveTree │ │ │ ├─┬ has-ansi@2.0.0
17 silly saveTree │ │ │ │ └── ansi-regex@2.1.1
17 silly saveTree │ │ │ └── supports-color@2.0.0
17 silly saveTree │ │ └── js-tokens@3.0.2
17 silly saveTree │ ├─┬ chokidar@2.1.6
17 silly saveTree │ │ ├─┬ anymatch@2.0.0
17 silly saveTree │ │ │ ├─┬ micromatch@3.1.10
17 silly saveTree │ │ │ │ ├── arr-diff@4.0.0
17 silly saveTree │ │ │ │ ├── array-unique@0.3.2
17 silly saveTree │ │ │ │ ├─┬ braces@2.3.2
17 silly saveTree │ │ │ │ │ ├── arr-flatten@1.1.0
17 silly saveTree │ │ │ │ │ ├─┬ extend-shallow@2.0.1
17 silly saveTree │ │ │ │ │ │ └── is-extendable@0.1.1
17 silly saveTree │ │ │ │ │ ├─┬ fill-range@4.0.0
17 silly saveTree │ │ │ │ │ │ ├── extend-shallow@2.0.1
17 silly saveTree │ │ │ │ │ │ ├─┬ is-number@3.0.0
17 silly saveTree │ │ │ │ │ │ │ └─┬ kind-of@3.2.2
17 silly saveTree │ │ │ │ │ │ │   └── is-buffer@1.1.6
17 silly saveTree │ │ │ │ │ │ └── repeat-string@1.6.1
17 silly saveTree │ │ │ │ │ ├── isobject@3.0.1
17 silly saveTree │ │ │ │ │ └── repeat-element@1.1.3
17 silly saveTree │ │ │ │ ├─┬ define-property@2.0.2
17 silly saveTree │ │ │ │ │ └─┬ is-descriptor@1.0.2
17 silly saveTree │ │ │ │ │   ├─┬ is-accessor-descriptor@1.0.0
17 silly saveTree │ │ │ │ │   │ └── kind-of@6.0.2
17 silly saveTree │ │ │ │ │   ├── is-data-descriptor@1.0.0
17 silly saveTree │ │ │ │ │   └── kind-of@6.0.2
17 silly saveTree │ │ │ │ ├─┬ extend-shallow@3.0.2
17 silly saveTree │ │ │ │ │ ├── assign-symbols@1.0.0
17 silly saveTree │ │ │ │ │ └─┬ is-extendable@1.0.1
17 silly saveTree │ │ │ │ │   └── is-plain-object@2.0.4
17 silly saveTree │ │ │ │ ├─┬ extglob@2.0.4
17 silly saveTree │ │ │ │ │ ├─┬ define-property@1.0.0
17 silly saveTree │ │ │ │ │ │ └─┬ is-descriptor@1.0.2
17 silly saveTree │ │ │ │ │ │   ├── is-accessor-descriptor@1.0.0
17 silly saveTree │ │ │ │ │ │   └── is-data-descriptor@1.0.0
17 silly saveTree │ │ │ │ │ ├─┬ expand-brackets@2.1.4
17 silly saveTree │ │ │ │ │ │ ├─┬ debug@2.6.9
17 silly saveTree │ │ │ │ │ │ │ └── ms@2.0.0
17 silly saveTree │ │ │ │ │ │ ├─┬ define-property@0.2.5
17 silly saveTree │ │ │ │ │ │ │ └─┬ is-descriptor@0.1.6
17 silly saveTree │ │ │ │ │ │ │   ├─┬ is-accessor-descriptor@0.1.6
17 silly saveTree │ │ │ │ │ │ │   │ └── kind-of@3.2.2
17 silly saveTree │ │ │ │ │ │ │   ├─┬ is-data-descriptor@0.1.4
17 silly saveTree │ │ │ │ │ │ │   │ └── kind-of@3.2.2
17 silly saveTree │ │ │ │ │ │ │   └── kind-of@5.1.0
17 silly saveTree │ │ │ │ │ │ ├── extend-shallow@2.0.1
17 silly saveTree │ │ │ │ │ │ ├── posix-character-classes@0.1.1
17 silly saveTree │ │ │ │ │ │ └── regex-not@1.0.2
17 silly saveTree │ │ │ │ │ ├── extend-shallow@2.0.1
17 silly saveTree │ │ │ │ │ ├─┬ fragment-cache@0.2.1
17 silly saveTree │ │ │ │ │ │ └── map-cache@0.2.2
17 silly saveTree │ │ │ │ │ └── regex-not@1.0.2
17 silly saveTree │ │ │ │ ├── fragment-cache@0.2.1
17 silly saveTree │ │ │ │ ├── kind-of@6.0.2
17 silly saveTree │ │ │ │ ├─┬ nanomatch@1.2.13
17 silly saveTree │ │ │ │ │ ├── is-windows@1.0.2
17 silly saveTree │ │ │ │ │ └── object.pick@1.3.0
17 silly saveTree │ │ │ │ ├── object.pick@1.3.0
17 silly saveTree │ │ │ │ └── regex-not@1.0.2
17 silly saveTree │ │ │ └─┬ normalize-path@2.1.1
17 silly saveTree │ │ │   └── remove-trailing-separator@1.1.0
17 silly saveTree │ │ ├── async-each@1.0.3
17 silly saveTree │ │ ├── braces@2.3.2
17 silly saveTree │ │ ├─┬ fsevents@1.2.9
17 silly saveTree │ │ │ ├── nan@2.14.0
17 silly saveTree │ │ │ └─┬ node-pre-gyp@0.12.0
17 silly saveTree │ │ │   ├── detect-libc@1.0.3
17 silly saveTree │ │ │   ├─┬ mkdirp@0.5.1
17 silly saveTree │ │ │   │ └── minimist@0.0.8
17 silly saveTree │ │ │   ├─┬ needle@2.3.0
17 silly saveTree │ │ │   │ ├─┬ debug@4.1.1
17 silly saveTree │ │ │   │ │ └── ms@2.1.1
17 silly saveTree │ │ │   │ ├─┬ iconv-lite@0.4.24
17 silly saveTree │ │ │   │ │ └── safer-buffer@2.1.2
17 silly saveTree │ │ │   │ └── sax@1.2.4
17 silly saveTree │ │ │   ├─┬ nopt@4.0.1
17 silly saveTree │ │ │   │ ├── abbrev@1.1.1
17 silly saveTree │ │ │   │ └─┬ osenv@0.1.5
17 silly saveTree │ │ │   │   ├── os-homedir@1.0.2
17 silly saveTree │ │ │   │   └── os-tmpdir@1.0.2
17 silly saveTree │ │ │   ├─┬ npm-packlist@1.4.1
17 silly saveTree │ │ │   │ ├─┬ ignore-walk@3.0.1
17 silly saveTree │ │ │   │ │ └─┬ minimatch@3.0.4
17 silly saveTree │ │ │   │ │   └─┬ brace-expansion@1.1.11
17 silly saveTree │ │ │   │ │     ├── balanced-match@1.0.0
17 silly saveTree │ │ │   │ │     └── concat-map@0.0.1
17 silly saveTree │ │ │   │ └── npm-bundled@1.0.6
17 silly saveTree │ │ │   ├─┬ npmlog@4.1.2
17 silly saveTree │ │ │   │ ├─┬ are-we-there-yet@1.1.5
17 silly saveTree │ │ │   │ │ ├── delegates@1.0.0
17 silly saveTree │ │ │   │ │ └─┬ readable-stream@2.3.6
17 silly saveTree │ │ │   │ │   ├── core-util-is@1.0.2
17 silly saveTree │ │ │   │ │   ├── inherits@2.0.3
17 silly saveTree │ │ │   │ │   ├── isarray@1.0.0
17 silly saveTree │ │ │   │ │   ├── process-nextick-args@2.0.0
17 silly saveTree │ │ │   │ │   ├── safe-buffer@5.1.2
17 silly saveTree │ │ │   │ │   ├── string_decoder@1.1.1
17 silly saveTree │ │ │   │ │   └── util-deprecate@1.0.2
17 silly saveTree │ │ │   │ ├── console-control-strings@1.1.0
17 silly saveTree │ │ │   │ ├─┬ gauge@2.7.4
17 silly saveTree │ │ │   │ │ ├── aproba@1.2.0
17 silly saveTree │ │ │   │ │ ├── has-unicode@2.0.1
17 silly saveTree │ │ │   │ │ ├── object-assign@4.1.1
17 silly saveTree │ │ │   │ │ ├── signal-exit@3.0.2
17 silly saveTree │ │ │   │ │ ├─┬ string-width@1.0.2
17 silly saveTree │ │ │   │ │ │ ├── code-point-at@1.1.0
17 silly saveTree │ │ │   │ │ │ ├─┬ is-fullwidth-code-point@1.0.0
17 silly saveTree │ │ │   │ │ │ │ └── number-is-nan@1.0.1
17 silly saveTree │ │ │   │ │ │ └─┬ strip-ansi@3.0.1
17 silly saveTree │ │ │   │ │ │   └── ansi-regex@2.1.1
17 silly saveTree │ │ │   │ │ ├── strip-ansi@3.0.1
17 silly saveTree │ │ │   │ │ └── wide-align@1.1.3
17 silly saveTree │ │ │   │ └── set-blocking@2.0.0
17 silly saveTree │ │ │   ├─┬ rc@1.2.8
17 silly saveTree │ │ │   │ ├── deep-extend@0.6.0
17 silly saveTree │ │ │   │ ├── ini@1.3.5
17 silly saveTree │ │ │   │ ├── minimist@1.2.0
17 silly saveTree │ │ │   │ └── strip-json-comments@2.0.1
17 silly saveTree │ │ │   ├─┬ rimraf@2.6.3
17 silly saveTree │ │ │   │ └─┬ glob@7.1.3
17 silly saveTree │ │ │   │   ├── fs.realpath@1.0.0
17 silly saveTree │ │ │   │   ├─┬ inflight@1.0.6
17 silly saveTree │ │ │   │   │ ├─┬ once@1.4.0
17 silly saveTree │ │ │   │   │ │ └── wrappy@1.0.2
17 silly saveTree │ │ │   │   │ └── wrappy@1.0.2
17 silly saveTree │ │ │   │   ├── once@1.4.0
17 silly saveTree │ │ │   │   └── path-is-absolute@1.0.1
17 silly saveTree │ │ │   ├── semver@5.7.0
17 silly saveTree │ │ │   └─┬ tar@4.4.8
17 silly saveTree │ │ │     ├── chownr@1.1.1
17 silly saveTree │ │ │     ├─┬ fs-minipass@1.2.5
17 silly saveTree │ │ │     │ └─┬ minipass@2.3.5
17 silly saveTree │ │ │     │   └── yallist@3.0.3
17 silly saveTree │ │ │     ├── minipass@2.3.5
17 silly saveTree │ │ │     ├── minizlib@1.2.1
17 silly saveTree │ │ │     └── yallist@3.0.3
17 silly saveTree │ │ ├─┬ glob-parent@3.1.0
17 silly saveTree │ │ │ ├─┬ is-glob@3.1.0
17 silly saveTree │ │ │ │ └── is-extglob@2.1.1
17 silly saveTree │ │ │ └── path-dirname@1.0.2
17 silly saveTree │ │ ├── inherits@2.0.4
17 silly saveTree │ │ ├─┬ is-binary-path@1.0.1
17 silly saveTree │ │ │ └── binary-extensions@1.13.1
17 silly saveTree │ │ ├── is-glob@4.0.1
17 silly saveTree │ │ ├── path-is-absolute@1.0.1
17 silly saveTree │ │ └─┬ readdirp@2.2.1
17 silly saveTree │ │   ├── graceful-fs@4.2.1
17 silly saveTree │ │   └─┬ readable-stream@2.3.6
17 silly saveTree │ │     ├── core-util-is@1.0.2
17 silly saveTree │ │     ├── isarray@1.0.0
17 silly saveTree │ │     └── process-nextick-args@2.0.1
17 silly saveTree │ ├── micromatch@3.1.10
17 silly saveTree │ └─┬ minimatch@3.0.4
17 silly saveTree │   └─┬ brace-expansion@1.1.11
17 silly saveTree │     ├── balanced-match@1.0.0
17 silly saveTree │     └── concat-map@0.0.1
17 silly saveTree ├─┬ html-loader@0.5.5
17 silly saveTree │ ├─┬ es6-templates@0.2.3
17 silly saveTree │ │ └─┬ recast@0.11.23
17 silly saveTree │ │   ├── ast-types@0.9.6
17 silly saveTree │ │   └── esprima@3.1.3
17 silly saveTree │ ├── fastparse@1.1.2
17 silly saveTree │ ├─┬ html-minifier@3.5.21
17 silly saveTree │ │ ├─┬ camel-case@3.0.0
17 silly saveTree │ │ │ └─┬ no-case@2.3.2
17 silly saveTree │ │ │   └── lower-case@1.1.4
17 silly saveTree │ │ ├─┬ clean-css@4.2.1
17 silly saveTree │ │ │ └── source-map@0.6.1
17 silly saveTree │ │ ├── commander@2.17.1
17 silly saveTree │ │ ├── he@1.2.0
17 silly saveTree │ │ ├── param-case@2.1.1
17 silly saveTree │ │ └── relateurl@0.2.7
17 silly saveTree │ └── object-assign@4.1.1
17 silly saveTree ├─┬ html-webpack-plugin@3.2.0
17 silly saveTree │ ├─┬ loader-utils@0.2.17
17 silly saveTree │ │ ├── big.js@3.2.0
17 silly saveTree │ │ └── json5@0.5.1
17 silly saveTree │ └─┬ pretty-error@2.1.1
17 silly saveTree │   └─┬ renderkid@2.0.3
17 silly saveTree │     ├─┬ css-select@1.2.0
17 silly saveTree │     │ ├── boolbase@1.0.0
17 silly saveTree │     │ ├── css-what@2.1.3
17 silly saveTree │     │ ├─┬ domutils@1.5.1
17 silly saveTree │     │ │ ├─┬ dom-serializer@0.2.1
17 silly saveTree │     │ │ │ ├── domelementtype@2.0.1
17 silly saveTree │     │ │ │ └── entities@2.0.0
17 silly saveTree │     │ │ └── domelementtype@1.3.1
17 silly saveTree │     │ └── nth-check@1.0.2
17 silly saveTree │     ├── dom-converter@0.2.0
17 silly saveTree │     └─┬ htmlparser2@3.10.1
17 silly saveTree │       ├── domhandler@2.4.2
17 silly saveTree │       ├── entities@1.1.2
17 silly saveTree │       └── readable-stream@3.4.0
17 silly saveTree ├─┬ http-server@0.11.1
17 silly saveTree │ ├── colors@1.0.3
17 silly saveTree │ ├── corser@2.0.1
17 silly saveTree │ ├─┬ ecstatic@3.3.2
17 silly saveTree │ │ └── mime@1.6.0
17 silly saveTree │ ├─┬ http-proxy@1.17.0
17 silly saveTree │ │ ├── eventemitter3@3.1.2
17 silly saveTree │ │ ├─┬ follow-redirects@1.7.0
17 silly saveTree │ │ │ └── debug@3.2.6
17 silly saveTree │ │ └── requires-port@1.0.0
17 silly saveTree │ ├── opener@1.4.3
17 silly saveTree │ ├─┬ optimist@0.6.1
17 silly saveTree │ │ └── minimist@0.0.10
17 silly saveTree │ └─┬ portfinder@1.0.21
17 silly saveTree │   ├── async@1.5.2
17 silly saveTree │   └─┬ debug@2.6.9
17 silly saveTree │     └── ms@2.0.0
17 silly saveTree ├─┬ mini-css-extract-plugin@0.8.0
17 silly saveTree │ ├─┬ normalize-url@1.9.1
17 silly saveTree │ │ ├── prepend-http@1.0.4
17 silly saveTree │ │ └── query-string@4.3.4
17 silly saveTree │ └─┬ schema-utils@1.0.0
17 silly saveTree │   ├── ajv-errors@1.0.1
17 silly saveTree │   ├── ajv-keywords@3.4.1
17 silly saveTree │   └─┬ ajv@6.10.2
17 silly saveTree │     ├── fast-deep-equal@2.0.1
17 silly saveTree │     ├── fast-json-stable-stringify@2.0.0
17 silly saveTree │     └── json-schema-traverse@0.4.1
17 silly saveTree └─┬ postcss-loader@3.0.0
17 silly saveTree   ├─┬ postcss-load-config@2.1.0
17 silly saveTree   │ ├─┬ cosmiconfig@5.2.1
17 silly saveTree   │ │ ├─┬ import-fresh@2.0.0
17 silly saveTree   │ │ │ └─┬ caller-path@2.0.0
17 silly saveTree   │ │ │   └─┬ caller-callsite@2.0.0
17 silly saveTree   │ │ │     └── callsites@2.0.0
17 silly saveTree   │ │ ├── is-directory@0.3.1
17 silly saveTree   │ │ ├─┬ js-yaml@3.13.1
17 silly saveTree   │ │ │ ├── argparse@1.0.10
17 silly saveTree   │ │ │ └── esprima@4.0.1
17 silly saveTree   │ │ └─┬ parse-json@4.0.0
17 silly saveTree   │ │   ├─┬ error-ex@1.3.2
17 silly saveTree   │ │   │ └── is-arrayish@0.2.1
17 silly saveTree   │ │   └── json-parse-better-errors@1.0.2
17 silly saveTree   │ └─┬ import-cwd@2.1.0
17 silly saveTree   │   └── import-from@2.1.0
17 silly saveTree   └── schema-utils@1.0.0
18 verbose stack TypeError: Cannot read property 'match' of undefined
18 verbose stack     at tarballToVersion (/usr/local/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:87:20)
18 verbose stack     at inflatableChild (/usr/local/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:99:22)
18 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:55:12
18 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
18 verbose stack     at Object.gotValue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:155:18)
18 verbose stack     at Object.gotAccum (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:144:25)
18 verbose stack     at Object.tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
18 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:517:31)
18 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
18 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
18 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)
18 verbose stack     at _drainQueueStep (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
18 verbose stack     at _drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
18 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
18 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
18 verbose stack     at processImmediate (internal/timers.js:456:21)
19 verbose cwd /Users/yu.wang/Documents/Workspace/webpack-workshop
20 verbose Darwin 19.3.0
21 verbose argv "/usr/local/Cellar/node/14.3.0/bin/node" "/usr/local/bin/npm" "install"
22 verbose node v14.3.0
23 verbose npm  v6.14.4
24 error Cannot read property 'match' of undefined
25 verbose exit [ 1, true ]
```

**Comment by 1hassanm** [comment]
@joeytat Deleting **lock** file and **node_modules** folder solved this issue for me.
